import {
  Bell,
  Blocks,
  BookOpen,
  Bot,
  BotMessageSquare,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleQuestionMark,
  CircleSlash,
  CircleX,
  ClipboardCopy,
  ClockAlert,
  Copy,
  Database,
  Ellipsis,
  Eye,
  EyeOff,
  Expand,
  FileKey,
  Filter,
  FlaskConical,
  Gauge,
  Globe,
  Info,
  RadioTower,
  Terminal,
  KeyRound,
  Library,
  List,
  Lock,
  LogIn,
  LogOut,
  Moon,
  Palette,
  Pencil,
  SquarePen,
  Plug,
  Plus,
  RefreshCw,
  RotateCcwKey,
  ScanSearch,
  Settings,
  ShieldAlert,
  ShieldMinus,
  ShieldPlus,
  ShieldX,
  Sparkles,
  Sun,
  Timer,
  TimerOff,
  Trash,
  TriangleAlert,
  Unplug,
  UserRoundCheck,
  UserRoundPlus,
  UserRoundX,
  X,
  Zap,
} from 'lucide';
import type { IconDefinition } from './icon';

export const LUCIDE_ICONS: Record<string, IconDefinition> = {
  blocks: { kind: 'lucide', node: Blocks, size: 15 },
  bookOpen: { kind: 'lucide', node: BookOpen, size: 15 },
  bot: { kind: 'lucide', node: Bot, size: 15 },
  botMessageSquare: { kind: 'lucide', node: BotMessageSquare, size: 15 },
  expand: { kind: 'lucide', node: Expand, size: 15 },
  eye: { kind: 'lucide', node: Eye, size: 14 },
  eyeOff: { kind: 'lucide', node: EyeOff, size: 14 },
  copy: { kind: 'lucide', node: Copy, size: 14 },
  check: { kind: 'lucide', node: Check, size: 13 },
  chevronDown: { kind: 'lucide', node: ChevronDown, size: 13 },
  chevronRight: { kind: 'lucide', node: ChevronRight, size: 13 },
  pencil: { kind: 'lucide', node: Pencil, size: 13 },
  squarePen: { kind: 'lucide', node: SquarePen, size: 14 },
  trash: { kind: 'lucide', node: Trash, size: 13 },
  gear: { kind: 'lucide', node: Settings, size: 15 },
  menubar: { kind: 'lucide', node: RotateCcwKey, size: 14 },
  bell: { kind: 'lucide', node: Bell, size: 15 },
  circleQuestion: { kind: 'lucide', node: CircleQuestionMark, size: 15 },
  circleCheck: { kind: 'lucide', node: CircleCheck, size: 15 },
  circleSlash: { kind: 'lucide', node: CircleSlash, size: 15 },
  circleX: { kind: 'lucide', node: CircleX, size: 15 },
  clipboardCopy: { kind: 'lucide', node: ClipboardCopy, size: 15 },
  clockAlert: { kind: 'lucide', node: ClockAlert, size: 15 },
  database: { kind: 'lucide', node: Database, size: 15 },
  ellipsis: { kind: 'lucide', node: Ellipsis, size: 15 },
  fileKey: { kind: 'lucide', node: FileKey, size: 15 },
  filter: { kind: 'lucide', node: Filter, size: 12 },
  flaskConical: { kind: 'lucide', node: FlaskConical, size: 15 },
  gauge: { kind: 'lucide', node: Gauge, size: 15 },
  globe: { kind: 'lucide', node: Globe, size: 15 },
  info: { kind: 'lucide', node: Info, size: 12 },
  terminal: { kind: 'lucide', node: Terminal, size: 15 },
  radioTower: { kind: 'lucide', node: RadioTower, size: 15 },
  keyRound: { kind: 'lucide', node: KeyRound, size: 12 },
  library: { kind: 'lucide', node: Library, size: 15 },
  list: { kind: 'lucide', node: List, size: 15 },
  lock: { kind: 'lucide', node: Lock, size: 15 },
  logIn: { kind: 'lucide', node: LogIn, size: 15 },
  logOut: { kind: 'lucide', node: LogOut, size: 15 },
  moon: { kind: 'lucide', node: Moon, size: 15 },
  sun: { kind: 'lucide', node: Sun, size: 15 },
  palette: { kind: 'lucide', node: Palette, size: 15 },
  plug: { kind: 'lucide', node: Plug, size: 15 },
  plugSm: { kind: 'lucide', node: Plug, size: 14 },
  plus: { kind: 'lucide', node: Plus, size: 12 },
  refresh: { kind: 'lucide', node: RefreshCw, size: 13 },
  scanSearch: { kind: 'lucide', node: ScanSearch, size: 15 },
  shieldAlert: { kind: 'lucide', node: ShieldAlert, size: 15 },
  shieldMinus: { kind: 'lucide', node: ShieldMinus, size: 15 },
  shieldPlus: { kind: 'lucide', node: ShieldPlus, size: 15 },
  shieldX: { kind: 'lucide', node: ShieldX, size: 15 },
  sparkles: { kind: 'lucide', node: Sparkles, size: 15 },
  timer: { kind: 'lucide', node: Timer, size: 15 },
  timerOff: { kind: 'lucide', node: TimerOff, size: 15 },
  triangleAlert: { kind: 'lucide', node: TriangleAlert, size: 12 },
  unplug: { kind: 'lucide', node: Unplug, size: 15 },
  userRoundCheck: { kind: 'lucide', node: UserRoundCheck, size: 15 },
  userRoundPlus: { kind: 'lucide', node: UserRoundPlus, size: 15 },
  userRoundX: { kind: 'lucide', node: UserRoundX, size: 15 },
  x: { kind: 'lucide', node: X, size: 13 },
  zap: { kind: 'lucide', node: Zap, size: 15 },
};
